---
# Title: role-gitea
#
# Author: bitfinity.nl
# File: tasks/03-gitea-config.yml.yml
#
# Description:
#   Gitea is a community managed lightweight code hosting solution written in Go.
#

- name: "Transfer template gitea/app.ini.j2 to /etc/gitea/app.ini"
  ansible.builtin.template:
    src: gitea/app.ini.j2
    dest: /etc/gitea/app.ini
    owner: root
    group: root
    mode: '0600'  
    backup: yes

#- name: ""
