---
# Title: role-gitea
#
# Author: bitfinity.nl
# File: tasks/05-gitea-ldap.yml
#
# Description:
#   Gitea is a community managed lightweight code hosting solution written in Go.
#

- name: "Check if authentication profile {{ gitea_ldap_name }} exists"
  #raw: sudo su - git -c 'gitea admin auth list -c /etc/gitea/app.ini | grep -o "{{ gitea_ldap_name }}"'
  ansible.builtin.command: "sudo su - git -c 'gitea admin auth list -c /etc/gitea/app.ini'"
  register: result_ldap_name

- name: "Configure Gitea for LDAP (BindDN) authentication" 
  raw: |
    sudo su - git -c "gitea admin auth add-ldap \
    --name {{ gitea_ldap_name }} \
    --security-protocol {{ gitea_ldap_security_protocol }} \
    --host {{ gitea_ldap_host}} \
    --port {{ gitea_ldap_port }} \
    --bind-dn '{{ gitea_bind_dn }}' \
    --bind-password {{ gitea_bind_password}} \
    --user-search-base {{ gitea_user_search_base }} \
    --user-filter '{{ gitea_user_filter }}' \
    --admin-filter '{{ gitea_admin_filter }}' \
    --username-attribute {{ gitea_username_attribute }} \
    --firstname-attribute {{ gitea_firstname_attribute }} \
    --surname-attribute {{ gitea_surname_attribute }}  \
    --email-attribute {{ gitea_email_attribute }} \
    --attributes-in-bind \
    --synchronize-users \
    -c /etc/gitea/app.ini"
  #no_log: true
  when: result_ldap_name.stdout == ""
