---
# Title: role-gitea
#
# Author: bitfinity.nl
# File: tasks/gitea-config.yml
#
# Description:
#   Gitea is a community managed lightweight code hosting solution written in Go.
#
# Sources:
#   https://gitea.io/

- name: "Configure /etc/gitea/app.ini - Application"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - Database-->"
    block: |
       APP_NAME = {{ gitea_app_name }}
       RUN_USER = {{ gitea_run_user }}
       RUN_MODE = {{ gitea_run_mode }}

- name: "Configure /etc/gitea/app.ini - database"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - Database-->"
    insertafter: "<body>"
    block: |
       [oauth2]
       JWT_SECRET = yo8DdzieF_wO6VCH6Nq965BWXx F-TsCuSydCrEthrdc

- name: "Configure /etc/gitea/app.ini - database"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - Database-->"
    insertafter: "<body>"
    block: |
       [database]
       DB_TYPE  = mysql
       HOST     = 127.0.0.1:3306
       NAME     = gitea
       USER     = gitea
       PASSWD   = password
       SSL_MODE = disable
       CHARSET  = utf8
       PATH     = /var/lib/gitea/data/gitea.db

- name: Configure /etc/gitea/app.ini - repository"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - repository-->"
    insertafter: "<body>"
    block: |
       [repository]
       ROOT = /home/git/gitea-repositories

- name: Configure /etc/gitea/app.ini - server"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - server-->"
    insertafter: "<body>"
    block: |
       [server]
       SSH_DOMAIN       = git.bitfinity.nl
       DOMAIN           = git.bitfinity.nl
       HTTP_PORT        = 3000
       ROOT_URL         = https://git.bitfinity.nl/
       DISABLE_SSH      = false
       SSH_PORT         = 22
       LFS_START_SERVER = true
       LFS_CONTENT_PATH = /var/lib/gitea/data/lfs
       LFS_JWT_SECRET   = SKq_HvXMOkkDkntkLtQq5rsx-5iyFWGr3VTMfGlvWdI
       OFFLINE_MODE     = false
 
- name: Configure /etc/gitea/app.ini - mailer"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - mailer-->"
    insertafter: "<body>"
    block: |
       ENABLED = true
       HOST    = smtp.bitfinity.nl
       FROM    = "Bitfinity Git repository" <git@bitfinity.nl>
       USER    = AuthenticatievoorGIT!
       PASSWD  = AuthenticatievoorGIT!
 
- name: Configure /etc/gitea/app.ini - service"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - service-->"
    insertafter: "<body>"
    block: |
       [service]
       REGISTER_EMAIL_CONFIRM            = false
       ENABLE_NOTIFY_MAIL                = true
       DISABLE_REGISTRATION              = false
       ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
       ENABLE_CAPTCHA                    = false
       REQUIRE_SIGNIN_VIEW               = true
       DEFAULT_KEEP_EMAIL_PRIVATE        = false
       DEFAULT_ALLOW_CREATE_ORGANIZATION = true
       DEFAULT_ENABLE_TIMETRACKING       = true
       NO_REPLY_ADDRESS                  = noreply@bitfinity.nl

- name: Configure /etc/gitea/app.ini - service"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - service-->"
    insertafter: "<body>"
    block: |
       [service]
       REGISTER_EMAIL_CONFIRM            = false
       ENABLE_NOTIFY_MAIL                = true
       DISABLE_REGISTRATION              = false
       ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
       ENABLE_CAPTCHA                    = false
       REQUIRE_SIGNIN_VIEW               = true
       DEFAULT_KEEP_EMAIL_PRIVATE        = false
       DEFAULT_ALLOW_CREATE_ORGANIZATION = true
       DEFAULT_ENABLE_TIMETRACKING       = true
       NO_REPLY_ADDRESS                  = noreply@bitfinity.nl

- name: Configure /etc/gitea/app.ini - openid"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - openid-->"
    insertafter: "<body>"
    block: |
       [openid]
       ENABLE_OPENID_SIGNIN = true
       ENABLE_OPENID_SIGNUP = true   

- name: Configure /etc/gitea/app.ini - session"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - session-->"
    insertafter: "<body>"
    block: | 
       [session]
       PROVIDER = file

- name: Configure /etc/gitea/app.ini - log"
  blockinfile:
    path: /var/www/html/index.html
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - log-->"
    insertafter: "<body>"
    block: |
       [log]
       MODE      = file
       LEVEL     = info
       ROOT_PATH = /var/lib/gitea/log
