---
# Title: role-gitea
#
# Author: bitfinity.nl
# File: tasks/main.yml
#
# Description:
#   Gitea is a community managed lightweight code hosting solution written in Go.
#

- name: "Create Gitea database and user"
  import_tasks: 01-mariadb-database.yml
  when:
    - ansible_architecture == "x86_64"
    
- name: "Prepare server for Gitea"
  import_tasks: 02-gitea.yml
  when:
    - ansible_architecture == "x86_64"
    
- name: "Prepare server for Gitea"
  import_tasks: 03-gitea-config.yml
  when:
    - ansible_architecture == "x86_64"

- name: "Install Apache2"
  import_tasks: 04-apache2.yml
  when:
    - ansible_architecture == "x86_64"

- name: "LDAP authentication"
  import_tasks: 05-gitea-ldap.yml
  when:
    - ansible_architecture == "x86_64"
    - gitea_ldap_state == "enabled"
    
